---

- name: "Include the '{{ jenkins_node_type }}' installation specific variables" 
  include_vars: "{{ jenkins_node_type }}.yml"
  
- name: Download latest JenkinsConfigAsCode plugin
  become: true
  get_url:
    url: https://updates.jenkins.io/latest/configuration-as-code.hpi
    dest: "/var/lib/{{ jenkins_user }}/plugins/configuration-as-code.hpi"
    mode: u=rw,g=r,o=r
    group: "{{ jenkins_user }}"
    owner: "{{ jenkins_user }}"

- name: Add the path to the configuration file
  become: true
  lineinfile:
    path: "/etc/default/{{ jenkins_user }}"
    regexp: '^CASC_JENKINS_CONFIG='
    insertafter: '^HTTP_PORT'
    line: 'CASC_JENKINS_CONFIG=/var/lib/cloudbees-core-oc/cfgAsCode/configuration.yaml'

- name: create directory for confifuration
  become: true
  file:
    path: "/var/lib/{{ jenkins_user }}/cfgAsCode"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: u=rwx,g=rx,o=rx
    

- name: copy the configuration file
  become: true
  copy:
    src: "oc-configuration.yaml"
    dest: "/var/lib/{{ jenkins_user }}/cfgAsCode/configuration.yaml"
    force: yes
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: u=rw,g=r,o=r
