---

- name: Download latest JenkinsConfigAsCode plugin
  become: true
  get_url:
    url: https://updates.jenkins.io/latest/configuration-as-code.hpi
    dest: /var/lib/cloudbees-core-oc/plugins/configuration-as-code.hpi
    mode: u=rw,g=r,o=r
    group: cloudbees-core-oc
    owner: cloudbees-core-oc

- name: Add the path to the configuration file
  become: true
  lineinfile:
    path: /etc/default/cloudbees-core-oc
    regexp: '^CASC_JENKINS_CONFIG='
    insertafter: '^HTTP_PORT'
    line: 'CASC_JENKINS_CONFIG=/var/lib/cloudbees-core-oc/cfgAsCode/configuration.yaml'

- name: create directory for confifuration
  become: true
  file:
    path: /var/lib/cloudbees-core-oc/cfgAsCode
    state: directory
    owner: cloudbees-core-oc
    group: cloudbees-core-oc
    mode: u=rwx,g=rx,o=rx
    

- name: copy the configuration file
  become: true
  copy:
    src: oc-configuration.yaml
    dest: /var/lib/cloudbees-core-oc/cfgAsCode/configuration.yaml
    force: yes
    owner: cloudbees-core-oc
    group: cloudbees-core-oc
    mode: u=rw,g=r,o=r
