---

- name: Load encrypted default admin password
  include_vars: "default_admin_password.yml"

#this assumes that the `init.groovy.d` directory has been previously created
- name: Update the initialize groovy and copy it to the target directory
  become: true
  template: 
    src: "initial_security.j2"
    dest: "/var/lib/{{ jenkins_user }}/init.groovy.d/000-initial_security.groovy"
    force: yes
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: u=rw,g=r,o=r   