---

- name: "Include the '{{ jenkins_node_type }}' installation specific variables" 
  include_vars: "{{ jenkins_node_type }}.yml"

- name: Add the {{ option_friendly_name }} APT Key
  become: true
  apt_key:
    url: "{{ key_url }}"
    state: present

- name: Add the {{ option_friendly_name }} package repository
  become: true
  apt_repository:
    repo: "{{ repo_url }}"
    state: present

# To force a particular version:  "{{ package_name }}=2.138.3.1"
- name: Install {{ option_friendly_name }}
  become: true
  apt:
    update_cache: yes
    name: "{{ package_name }}"


- name: Add the auto incremental update flag to startup
  become: true
  lineinfile:
    path: "/etc/default/{{ package_name }}"
    regexp: '^JAVA_ARGS="-Djava.awt.headless=true"'
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Dcb.BeekeeperProp.autoInstallIncremental=true"'


# restart the service so that an available incremental update is picked up (especially when reapplying 
#   the script to a running system)
- name: restart the {{ package_name }} service 
  become: true
  service:
    name: "{{ package_name }}"
    state: restarted


- name: redirect the traffic from 80 to {{ used_port }} with IPtables
  become: yes
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: "{{ used_port }}"
    comment: "Redirect web traffic to port {{ used_port }}"


