---

- name: ensure python 2.7 is installed
  raw: sudo apt-get install -y python2.7 python-simplejson
   
# try pinging the system now
- name: Trying if the Ansible communication works now (using a Ping)
  ping:

- name: Gathering facts
  setup:

## Used to validate that it is possible to install a package and that everything is working fine
# - name: Install COWSAY
#   become: true
#   apt: 
#     update_cache: yes
#     name: cowsay
# - name: let the cow say hello
#   command: cowsay hello, world!
#   register: cowsay_out
# - debug: var=cowsay_out.stdout_lines

- name: Install OpenJdk 8 (JRE)
  become: true
  apt:
    update_cache: yes
    name: openjdk-8-jre

## Setup the IP tables

- name: Install the `iptables` package
  become: yes
  package:
    name: iptables
    state: latest

- name: Flush existing firewall rules
  become: yes
  iptables:
    flush: true

- name: Firewall rule - allow all loopback traffic
  become: yes
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Firewall rule - allow port ping traffic
  become: yes
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp

- name: Firewall rule - allow port 22/SSH traffic
  become: yes
  iptables:
    chain: INPUT
    destination_port: 22
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - allow port 80/HTTP traffic
  become: yes
  iptables:
    chain: INPUT
    destination_port: 80
    jump: ACCEPT
    protocol: tcp

- name: Firewall rule - allow port 443/HTTPS traffic
  become: yes
  iptables:
    chain: INPUT
    destination_port: 443
    jump: ACCEPT
    protocol: tcp


- name: Firewall rule - allow port 50000 traffic
  become: yes
  iptables:
    chain: INPUT
    destination_port: 50000
    jump: ACCEPT
    protocol: tcp

# - name: Firewall rule - drop any traffic without rule
#   become: yes
#   iptables:
#     chain: INPUT
#     jump: DROP

- name: Install `netfilter-persistent` && `iptables-persistent` packages
  package:
      name: "{{item}}"
      state: present
  with_items:
      - iptables-persistent
      - netfilter-persistent
  when: ansible_os_family == "Debian"
  become: yes

- name: set VIMs background to dark by default
  lineinfile:
    path: "/home/ubuntu/.vimrc"
    create: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: u=rw,g=r,o=r
    insertafter: EOF
    line: ':set background=dark'
