---

- name: ensure python 2.7 is installed
  raw: sudo apt-get install -y python2.7 python-simplejson
   
# try pinging the system now
- name: Trying if the Ansible communication works now (using a Ping)
  ping:

- name: Gathering facts
  setup:

## Used to validate that it is possible to install a package and that everything is working fine
# - name: Install COWSAY
#   become: true
#   apt: 
#     update_cache: yes
#     name: cowsay
# - name: let the cow say hello
#   command: cowsay hello, world!
#   register: cowsay_out
# - debug: var=cowsay_out.stdout_lines

- name: Install OpenJdk 8 (JRE)
  become: true
  apt:
    update_cache: yes
    name: openjdk-8-jre

- name: set VIMs background to dark by default
  lineinfile:
    path: "/home/ubuntu/.vimrc"
    create: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: u=rw,g=r,o=r
    insertafter: EOF
    line: ':set background=dark'

- name: Start setting up the IP Tables
  include_tasks: iptables-task.yml