plugins:
  sites:
  - id: "cjoc-offline"
    url: "file:/var/cache/cloudbees-core-oc/war/WEB-INF/plugins/update-center.json"
  - id: "cap-cjoc"
    url: "https://jenkins-updates.cloudbees.com/update-center/envelope-cjoc/update-center.json"
jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  agentProtocols:
  - "Diagnostic-Ping"
  - "JNLP4-connect"
  - "MultiMaster"
  - "OperationsCenter2"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 2
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
security:
  globalconfigurationimpl:
    global:
      'no':
        canCustomMapping: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    defaultProperties:
    - installSource:
        installers:
        - jdkInstaller:
            acceptLicense: false
