---

- name: Add the CloudBees Core Client Master APT Key
  become: true
  apt_key:
    url: https://downloads.cloudbees.com/cloudbees-core/traditional/client-master/rolling/debian/cloudbees.com.key
    state: present

- name: Add the ClouBees Core Client Master package repository
  become: true
  apt_repository:
    repo: deb https://downloads.cloudbees.com/cloudbees-core/traditional/client-master/rolling/debian binary/
    state: present

- name: Install CloudBees Core Client Master
  become: true
  apt:
    update_cache: yes
    name: cloudbees-core-cm