- hosts: jmm_cjoc

  # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  gather_facts: False

  vars:
    jenkins_node_type: "cjoc"

  roles:
    - general
    - jenkinsCore
    - JenkinsConfigAsCode


- hosts: jmm_client_master

  # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  gather_facts: False

  vars:
    jenkins_node_type: "master"

  roles:
    - general
    - jenkinsCore    
    #- client_master