- hosts: jmm_cjoc

  # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  gather_facts: False

  roles:
    - general

  tasks:
    - name: Install CloudBees Core Operation Center
      become: true
      apt:
        update_cache: yes
        name: cloudbees-core-oc

- hosts: jmm_client_master

  # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  gather_facts: False

  roles:
    - general