- hosts: jmm_cjoc-eip

  # this is required as only python3 is installed on Ubuntu AMI
  gather_facts: False

  tasks:
    
    # try pinging the system now
    - ping:

    - name: ensure python 2.7 is installed
      raw: sudo apt-get install -y python2.7 python-simplejson
   
    - name: Install COWSAY
      become: true
      apt: 
        update_cache: yes
        name: cowsay
    - name: let the cow say hello
      command: cowsay hello, world!
      register: cowsay_out
    - debug: var=cowsay_out.stdout_lines

    - name: Install OpenJdk 8 (JRE)
      become: true
      apt:
        update_cache: yes
        name: openjdk-8-jre

    - name: Add the CloudBees APT Key
      become: true
      apt_key:
        url: https://downloads.cloudbees.com/cloudbees-core/traditional/operations-center/rolling/debian/cloudbees.com.key
        state: present

    - name: Add the ClouBees package repository
      become: true
      apt_repository:
        repo: deb https://downloads.cloudbees.com/cloudbees-core/traditional/operations-center/rolling/debian binary/
        state: present
    
    - name: Install CloudBees Core Operation Center
      become: true
      apt:
        update_cache=yes
        name=cloudbees-core-oc