---

- name: Add the CloudBees Core OC APT Key
  become: true
  apt_key:
    url: https://downloads.cloudbees.com/cloudbees-core/traditional/operations-center/rolling/debian/cloudbees.com.key
    state: present

- name: Add the ClouBees Core OC package repository
  become: true
  apt_repository:
    repo: deb https://downloads.cloudbees.com/cloudbees-core/traditional/operations-center/rolling/debian binary/
    state: present

- name: Install CloudBees Core Operation Center
  become: true
  apt:
    update_cache: yes
    name: cloudbees-core-oc


